const tarotDeck = [
    // Major Arcana (22 cards)
    { id: 'maj00', name: 'The Fool', img: 'cards/00.png' },
    { id: 'maj01', name: 'The Magician', img: 'cards/01.png' },
    { id: 'maj02', name: 'The High Priestess', img: 'cards/02.png' },
    { id: 'maj03', name: 'The Empress', img: 'cards/03.png' },
    { id: 'maj04', name: 'The Emperor', img: 'cards/04.png' },
    { id: 'maj05', name: 'The Hierophant', img: 'cards/05.png' },
    { id: 'maj06', name: 'The Lovers', img: 'cards/06.png' },
    { id: 'maj07', name: 'The Chariot', img: 'cards/07.png' },
    { id: 'maj08', name: 'Strength', img: 'cards/08.png' },
    { id: 'maj09', name: 'The Hermit', img: 'cards/09.png' },
    { id: 'maj10', name: 'Wheel of Fortune', img: 'cards/10.png' },
    { id: 'maj11', name: 'Justice', img: 'cards/11.png' },
    { id: 'maj12', name: 'The Hanged Man', img: 'cards/12.png' },
    { id: 'maj13', name: 'Death', img: 'cards/13.png' },
    { id: 'maj14', name: 'Temperance', img: 'cards/14.png' },
    { id: 'maj15', name: 'The Devil', img: 'cards/15.png' },
    { id: 'maj16', name: 'The Tower', img: 'cards/16.png' },
    { id: 'maj17', name: 'The Star', img: 'cards/17.png' },
    { id: 'maj18', name: 'The Moon', img: 'cards/18.png' },
    { id: 'maj19', name: 'The Sun', img: 'cards/19.png' },
    { id: 'maj20', name: 'Judgement', img: 'cards/20.png' },
    { id: 'maj21', name: 'The World', img: 'cards/21.png' },
    // Wands (14 cards)
    { id: 'wan01', name: 'Ace of Wands', img: 'cards/w1.png' },
    { id: 'wan02', name: 'Two of Wands', img: 'cards/w2.png' },
    { id: 'wan03', name: 'Three of Wands', img: 'cards/w3.png' },
    { id: 'wan04', name: 'Four of Wands', img: 'cards/w4.png' },
    { id: 'wan05', name: 'Five of Wands', img: 'cards/w5.png' },
    { id: 'wan06', name: 'Six of Wands', img: 'cards/w6.png' },
    { id: 'wan07', name: 'Seven of Wands', img: 'cards/w7.png' },
    { id: 'wan08', name: 'Eight of Wands', img: 'cards/w8.png' },
    { id: 'wan09', name: 'Nine of Wands', img: 'cards/w9.png' },
    { id: 'wan10', name: 'Ten of Wands', img: 'cards/w10.png' },
    { id: 'wan_p', name: 'Page of Wands', img: 'cards/w11.png' },
    { id: 'wan_k', name: 'Knight of Wands', img: 'cards/w12.png' },
    { id: 'wan_q', name: 'Queen of Wands', img: 'cards/w13.png' },
    { id: 'wan_K', name: 'King of Wands', img: 'cards/w14.png' },
    // Cups (14 cards)
    { id: 'cup01', name: 'Ace of Cups', img: 'cards/c1.png' },
    { id: 'cup02', name: 'Two of Cups', img: 'cards/c2.png' },
    { id: 'cup03', name: 'Three of Cups', img: 'cards/c3.png' },
    { id: 'cup04', name: 'Four of Cups', img: 'cards/c4.png' },
    { id: 'cup05', name: 'Five of Cups', img: 'cards/c5.png' },
    { id: 'cup06', name: 'Six of Cups', img: 'cards/c6.png' },
    { id: 'cup07', name: 'Seven of Cups', img: 'cards/c7.png' },
    { id: 'cup08', name: 'Eight of Cups', img: 'cards/c8.png' },
    { id: 'cup09', name: 'Nine of Cups', img: 'cards/c9.png' },
    { id: 'cup10', name: 'Ten of Cups', img: 'cards/c10.png' },
    { id: 'cup_p', name: 'Page of Cups', img: 'cards/c11.png' },
    { id: 'cup_k', name: 'Knight of Cups', img: 'cards/c12.png' },
    { id: 'cup_q', name: 'Queen of Cups', img: 'cards/c13.png' },
    { id: 'cup_K', name: 'King of Cups', img: 'cards/c14.png' },
    // Swords (14 cards)
    { id: 'swo01', name: 'Ace of Swords', img: 'cards/s1.png' },
    { id: 'swo02', name: 'Two of Swords', img: 'cards/s2.png' },
    { id: 'swo03', name: 'Three of Swords', img: 'cards/s3.png' },
    { id: 'swo04', name: 'Four of Swords', img: 'cards/s4.png' },
    { id: 'swo05', name: 'Five of Swords', img: 'cards/s5.png' },
    { id: 'swo06', name: 'Six of Swords', img: 'cards/s6.png' },
    { id: 'swo07', name: 'Seven of Swords', img: 'cards/s7.png' },
    { id: 'swo08', name: 'Eight of Swords', img: 'cards/s8.png' },
    { id: 'swo09', name: 'Nine of Swords', img: 'cards/s9.png' },
    { id: 'swo10', name: 'Ten of Swords', img: 'cards/s10.png' },
    { id: 'swo_p', name: 'Page of Swords', img: 'cards/s11.png' },
    { id: 'swo_k', name: 'Knight of Swords', img: 'cards/s12.png' },
    { id: 'swo_q', 'name': 'Queen of Swords', img: 'cards/s13.png' },
    { id: 'swo_K', name: 'King of Swords', img: 'cards/s14.png' },
    // Pentacles (14 cards)
    { id: 'pen01', name: 'Ace of Pentacles', img: 'cards/p1.png' },
    { id: 'pen02', name: 'Two of Pentacles', img: 'cards/p2.png' },
    { id: 'pen03', name: 'Three of Pentacles', img: 'cards/p3.png' },
    { id: 'pen04', name: 'Four of Pentacles', img: 'cards/p4.png' },
    { id: 'pen05', name: 'Five of Pentacles', img: 'cards/p5.png' },
    { id: 'pen06', name: 'Six of Pentacles', img: 'cards/p6.png' },
    { id: 'pen07', name: 'Seven of Pentacles', img: 'cards/p7.png' },
    { id: 'pen08', name: 'Eight of Pentacles', img: 'cards/p8.png' },
    { id: 'pen09', name: 'Nine of Pentacles', img: 'cards/p9.png' },
    { id: 'pen10', name: 'Ten of Pentacles', img: 'cards/p10.png' },
    { id: 'pen_p', name: 'Page of Pentacles', img: 'cards/p11.png' },
    { id: 'pen_k', name: 'Knight of Pentacles', img: 'cards/p12.png' },
    { id: 'pen_q', name: 'Queen of Pentacles', img: 'cards/p13.png' },
    { id: 'pen_K', name: 'King of Pentacles', img: 'cards/p14.png' }
];